apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment-00
spec:
  replicas: 1
  selector:
    matchLabels:
      component: yolo0
  template:
    metadata:
      labels:
        component: yolo0
    spec:
      containers:
      - name: yolo0
        image: ngoclam9412/unilever:yolo_microservice
        resources:
          limits:
            memory: "2Gi"
            cpu: "2"
            nvidia.com/gpu: 1
        ports:
        - containerPort: 8881
      nodeName: unilevercv
      
